# -*- coding: utf-8 -*-
"""Meu primeiro algoritmo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8Fqiy2Pi02Aad3LgU59q09F1zG-SlgS

# Operadores Aritméticos
"""

# Adicão
10 + 2

# Subtração
10 - 2

# Multiplicação
10 * 2

# Divisão
10 / 2

# Divisão inteira
10 // 2

# Resto da divisão
10 % 2

# Ponteciação
10 ** 2

"""# Operadores Relacionais"""

# Menor
10 < 2

# Menor ou igual
10 <= 2

# Maior
10 > 2

# Maior ou igual
10 >= 2

# Igual (1 "igual" é atribuição | 2 "Iguais" é igual)
7 == 7

# Diferente
7 != 7

"""# Operadores lógicos

*   And
*   Or
*   Not

# Tabela verdade

And
"""

print (10 > 2 and 4 < 6)    # V and V - V
print (10 > 2 and 4 > 6)    # V and F - F
print (10 < 2 and 4 < 6)    # F and V - F
print (10 < 2 and 4 > 6)    # F and F - F

"""Or"""

print (10 > 2 or 4 < 6)     # V or V - V
print (10 > 2 or 4 > 6)     # V or F - V
print (10 < 2 or 4 < 6)     # F or V - V
print (10 < 2 or 4 > 6)     # F or F - F

"""Not"""

not 10 > 2    # V - F #Not inverte a resposta (o que é verdadeiro/falso vira falso/verdadeiro)

not 10 < 2    # F - V

"""**Variáveis**

Variáveis estão alocadas em espaços na memória
"""

# Nome da variável é "x" que armazena o valor 10 em um espaço na memória
x = 10

print (x) #Utilizar a referencia no nome atribuído

"""Regras

# Case Sensitive
A !=a

**Boas Práticas com Variáveis**



> Exemplo: Multiplicação de 2 números

Não usar


*   Multiplicação
*   MultiplicacaoDeDoisNumeros
*   m

Usar

*   multiplicacao
*   mult
*   mult_total (snake_case)

**Visualização de Variáveis e Texto**
"""

print('Conhecendo o comando Print')

x = 8
print (x)

y = 10
soma = x + y
print(soma)

nome = 'Israel Gomes'
print (nome)

"""Concatenação"""

x = 5
print('o valor de x é', x)

print('O valor de x é', x, 'e o dobro é', x * 2)

print('Eu,', nome, 'tirei', x, 'na prova de Python')

y = 10; z = 20 + x - y

print('Declarar várias variáveis na mesma linha:', y, z)

"""Type

---


"""

x = 10
type(x)
print('x', type (x))

nome = 'Israel'
print('nome', type(nome))

num = '100' #Aqui era um número
num_convert = int(num) #Converter variável
print('num', type(num)) #Str virou num
print('num_conver', type(num_convert))

num_float = float(num)
print('num_float', num_float)

"""Input


*   Armazenar a informação digitada pelo usuário em uma variável
*   O dado armazenado sempre será um texto


"""

nome = input("Digite o nome do usuário ") #Aguarde o usuário digitar algo
print(nome)

valor = input('Digite a nota ')

print (nome, 'sua nota foi:', valor)

valor = input('Digite o valor do produto: ')
print(valor)

desconto = valor - 5

valor_convert = int(valor)
desconto = valor_convert - 5
print(desconto)

desconto = int(valor) - 5
print(desconto)

"""# Condicional"""

#if
if 5 < 10:
  print('Verdade')

# If/else
num1 = 10
num2 = 5
if num1 > num2:
    print('O num1 é o maior número')
else:
    print('O num2 é o maior número')

# If / Elif / Else
num1 = 10
num2 = 10
if num1 > num2:
    print('O num1 é o maior número')
elif num1 < num2:
    print('O num2 é o maior número')
else:
    print('Os dois são iguais')

"""# Condicional com operadores lógicos"""

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
    print('O num1 é o maior número')
else:
    print('O num1 não é o maior número')

"""#Listas, tuplas e dicionários"""

# Lista
[1,2,3,4,5]

# Tupla
(1,2,3,4,5)

# Dicionário
{'num1': 1, 'num2': 2}

"""# Lista"""

lista = [5, 'Israel', 8.9] # A lista começa na posição "zero" | 5 = 0, Israel = 1, etc

type(lista)

lista.append("Augusto") # Adicionar um elemento na lista (final da lista)

print(lista)
print(lista[1]) #Qual item eu quero imprimir?

"""# Tupla"""

tupla = (5, 'Israel', 8.9) # Os valores não podem ser modificados // Usado quando os valores não puderem ser alterados

type(tupla)

tupla.append("Augusto")

print(tupla)

"""# Dicionário"""

dicionario = {'nome': 'Israel','cidade': 'São Paulo'}

type(dicionario)

print(dicionario)

print(dicionario["nome"]) #Diferente da tupla, aqui não usamos campos e sim a chame ex.: "Nome"

dicionario['ultimo_nome'] = 'Gomes'

print(dicionario)

"""# Estrutura de repetição"""

# For range
for contador in range(10):
    print(contador)

# For range + break
for contador in range(1000):
    print(contador)
    if contador == 2:
        break

lista = ["Teste1", "Teste2"]

# For simples
for val in lista:
    print(val)

# For with enumerate
for i, val in enumerate(lista): #Preciso colocar quem vai ser o índice e atrelar ao contador
    print(i, val)

"""# For com operadores compostos"""

lista2 = [2, 3, 4] #Defini a lista

for val in lista2:
    val += 1
    print(val)

for val in lista2:
    val *= 2
    print(val)

"""# While"""

val = 1
while (val < 6): # Aqui no caso ele vai printar todos os números menor que 6 (8 é menor que 6? Não! Então ele para)
    val *=2
    print (val)

# While com else
val = 10
while val < 6:
    val *=2
else:
    print('Valor de val é', val)

# Solicita o nome do usuário e o exibe
nome_usuario = input("Por favor, insira seu nome: ")
print(f"Olá, {nome_usuario}! Bem-vindo ao nosso sistema.")

# Solicita a idade do usuário e converte para inteiro
idade_usuario = int(input("Por favor, insira sua idade: "))

# Verifica se o usuário é maior de idade
if idade_usuario >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")