# -*- coding: utf-8 -*-
"""Interação com usuário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11914n7cfP5xSQoC2imaTu5rOU_9mFqlg

# Nova seção
"""

# Lista dos alunos
notas = [85, 92, 78, 90, 88]

# Calcula a média das notas
soma = 0
for nota in notas:
    soma += nota
media = soma / len(notas)

# Classifique os alunos com base na média
alunos_aprovados = []
alunos_reprovados = []
for nota in notas:
    if nota >= media:
        alunos_aprovados.append(nota)
    else:
        alunos_reprovados.append(nota)

# Imprime os resultados
print("Nota dos alunos", notas)
print("Média das notas:", media)
print("Alunos aprovados:", alunos_aprovados)
print("Alunos reprovados:", alunos_reprovados)

"""# Estudando inputs"""

# Solicita o nome do usuário e o exibe
nome_usuario = input("Por favor, insira seu nome: ")
print(f"Olá, {nome_usuario}! Bem-vindo ao nosso sistema.")

# Solicita a idade do usuário e converte para inteiro
idade_usuario = int(input("Por favor, insira sua idade: "))

# Verifica se o usuário é maior de idade
if idade_usuario >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")