# -*- coding: utf-8 -*-
"""Estrutura condicional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_nzUohfm1lUKzDlKXhbNTtZIICEsbuM

# Condicional
"""

#if
if 5 < 10:
  print('Verdade')

# If/else
num1 = 10
num2 = 5
if num1 > num2:
    print('O num1 é o maior número')
else:
    print('O num2 é o maior número')

# If / Elif / Else
num1 = 10
num2 = 10
if num1 > num2:
    print('O num1 é o maior número')
elif num1 < num2:
    print('O num2 é o maior número')
else:
    print('Os dois são iguais')

"""# Condicional com operadores lógicos"""

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
    print('O num1 é o maior número')
else:
    print('O num1 não é o maior número')

"""#Listas, tuplas e dicionários"""

# Lista
[1,2,3,4,5]

# Tupla
(1,2,3,4,5)

# Dicionário
{'num1': 1, 'num2': 2}

"""# Lista"""

lista = [5, 'Israel', 8.9] # A lista começa na posição "zero" | 5 = 0, Israel = 1, etc

type(lista)

lista.append("Augusto") # Adicionar um elemento na lista (final da lista)

print(lista)
print(lista[1]) #Qual item eu quero imprimir?

"""# Tupla"""

tupla = (5, 'Israel', 8.9) # Os valores não podem ser modificados // Usado quando os valores não puderem ser alterados

type(tupla)

tupla.append("Augusto")

print(tupla)

"""# Dicionário"""

dicionario = {'nome': 'Israel','cidade': 'São Paulo'}

type(dicionario)

print(dicionario)

print(dicionario["nome"]) #Diferente da tupla, aqui não usamos campos e sim a chame ex.: "Nome"

dicionario['ultimo_nome'] = 'Gomes'

print(dicionario)

"""# Estrutura de repetição"""

# For range
for contador in range(10):
    print(contador)

# For range + break
for contador in range(1000):
    print(contador)
    if contador == 2:
        break

lista = ["Teste1", "Teste2"]

# For simples
for val in lista:
    print(val)

# For with enumerate
for i, val in enumerate(lista): #Preciso colocar quem vai ser o índice e atrelar ao contador
    print(i, val)

"""# For com operadores compostos"""

lista2 = [2, 3, 4] #Defini a lista

for val in lista2:
    val += 1
    print(val)

for val in lista2:
    val *= 2
    print(val)

"""# While"""

val = 1
while (val < 6): # Aqui no caso ele vai printar todos os números menor que 6 (8 é menor que 6? Não! Então ele para)
    val *=2
    print (val)

# While com else
val = 10
while val < 6:
    val *=2
else:
    print('Valor de val é', val)

# Solicita o nome do usuário e o exibe
nome_usuario = input("Por favor, insira seu nome: ")
print(f"Olá, {nome_usuario}! Bem-vindo ao nosso sistema.")

# Solicita a idade do usuário e converte para inteiro
idade_usuario = int(input("Por favor, insira sua idade: "))

# Verifica se o usuário é maior de idade
if idade_usuario >= 18:
    print("Você é maior de idade.")
else:
    print("Você é menor de idade.")